---
- name: deploy through tomcat
  hosts: localhost
  become: yes
  tasks:
    - name: copying warfile
      copy:
        src: target/SpringRestIntegrationApp-0.0.1-SNAPSHOT.war
        dest: /root/tomcat10/webapps/myapp.war